name: acha
description: "ACHA App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  intl: ^0.20.1
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16

  dio: ^5.7.0
  url_launcher: ^6.3.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2

  auto_size_text: ^3.0.0
  stacked_list_carousel: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/svgs/
    - lib/assets/svgs/signin/
    - lib/assets/svgs/modal/main/
    - lib/assets/svgs/navigation/

  fonts:
    - family: Pretendard
      fonts:
        - asset: lib/assets/fonts/pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/pretendard/Pretendard-Black.ttf
          weight: 900

    - family: Suit
      fonts:
        - asset: lib/assets/fonts/suit/SUIT-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/suit/SUIT-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/suit/SUIT-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/suit/SUIT-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/suit/SUIT-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/suit/SUIT-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/suit/SUIT-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/suit/SUIT-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/suit/SUIT-Heavy.ttf
          weight: 900