name: acha
description: "ACHA App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  intl: ^0.20.1
  collection: ^1.19.0
  dio: ^5.7.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.5
  equatable: ^2.0.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.2
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1

  url_launcher: ^6.3.0
  flutter_svg: ^2.0.16
  lottie: ^3.2.0
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  stacked_list_carousel: ^1.0.1
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/acha/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/images/modal/terms/
    - lib/assets/svgs/
    - lib/assets/svgs/auth/
    - lib/assets/svgs/modal/main/
    - lib/assets/svgs/modal/terms/
    - lib/assets/svgs/course/
    - lib/assets/svgs/notice/
    - lib/assets/svgs/mypage/
    - lib/assets/svgs/navigation/
    - lib/assets/svgs/toast/
    - lib/assets/lotties/auth/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: lib/assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: lib/assets/fonts/NotoSansKR-ExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: lib/assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/NotoSansKR-Black.otf
          weight: 900